[book]
authors = ["Jacob Halsey"]
language = "en"
multilingual = false
src = "src"
title = "The Jerusalem Book"

[preprocessor.bibliography]
command = "rust-script --debug src/bibliography.rs src/bibliography.bib src/ieee.csl"
