[book]
authors = ["Jacob Halsey"]
language = "en"
multilingual = false
src = "src"
title = "The Jerusalem Book"

[preprocessor.bibliography]
command = "mdbook-bibfile-referencing src/bibliography.bib src/ieee.csl --link-citations --flavour commonmark"

[output.html]
additional-css = ["src/custom.css"]
site-url = "/jerusalem-book/"

[output.linkcheck]
warning-policy = "error"
