name: mdBook

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jacob-pro/mdbook-bibfile-referencing:latest
    steps:
      - uses: actions/checkout@v2

      - name: Check book
        run: make check

      - name: Build book
        run: make build

      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
