name: mdBook

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/jacob-pro/mdbook-bibfile-referencing:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(ls)
      - run: mdbook-bibfile-referencing --help
      - run: pandoc --version
      - run: mdbook build

#      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
#        name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./book
